(define (problem final-house)
	(:domain walls)
	(:objects 
	c-1 c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 - count
	)
	(:init
	(= (block-at-inventory oak-wood) 70) (= (block-at-inventory spruce-wood-plank) 90) 
	(= (block-at-inventory spruce-wood-slab) 140) (= (block-at-inventory spruce-wood-stair) 80)
	(= (block-at-inventory brick) 80) (= (block-at-inventory oak-wood-plank) 80)
	(= (block-at-inventory oak-door) 20) (= (block-at-inventory glass-pane) 30)
	(= (block-at-inventory oak-wood-stair) 30) (= (block-at-inventory oak-leaf) 100)
	(= (block-at-inventory oak-fence) 70) (= (block-at-inventory torch) 35)
	(= (block-at-inventory wooden-pressure-plate) 10) (= (total-cost) 0) 
	(up c0 c-1) (up c1 c0) (up c2 c1) (up c3 c2) (up c4 c3) (up c5 c4)
	(right c1 c0) (right c2 c1) (right c3 c2) (right c4 c3) (right c5 c4) (right c6 c5) (right c7 c6) 
	(right c8 c7) (right c9 c8) (right c10 c9) (right c11 c10)
	(front c1 c0) (front c2 c1) (front c3 c2) (front c4 c3) (front c5 c4) (front c6 c5) (front c7 c6) 
	(front c8 c7) (front c9 c8) (front c10 c9) (front c11 c10)
	(block-at brick c4 c0 c8) (block-at spruce-wood-slab c3 c0 c2) (block-at spruce-wood-slab c10 c3 c4)
	(block-at spruce-wood-slab c3 c3 c10) (block-at spruce-wood-slab c10 c5 c7) (block-at spruce-wood-stair c10 c4 c6)
	(block-at oak-leaf c11 c0 c11) (block-at oak-leaf c11 c1 c11) (block-at spruce-wood-slab c6 c3 c3)
	(block-at spruce-wood-plank c10 c0 c2)
	(block-at grass c1 c-1 c1)
	(block-at grass c2 c-1 c1)
	(block-at grass c3 c-1 c1)
	(block-at grass c4 c-1 c1)
	
	(block-at grass c5 c-1 c1)
	(block-at grass c6 c-1 c1)
	(block-at grass c7 c-1 c1)
	(block-at grass c8 c-1 c1)
	
	(block-at grass c9 c-1 c1)
	(block-at grass c10 c-1 c1)
 	(block-at grass c11 c-1 c1)
 	(block-at grass c1 c-1 c2)
 
	(block-at grass c1 c-1 c3)
 	(block-at grass c1 c-1 c4)
 	(block-at grass c1 c-1 c5)
	(block-at grass c1 c-1 c6)
	
	(block-at grass c1 c-1 c7)
	(block-at grass c1 c-1 c8)
	(block-at grass c1 c-1 c9)
	(block-at grass c1 c-1 c10)
	
	(block-at grass c1 c-1 c11)
 	(block-at grass c2 c-1 c11)
 	(block-at grass c3 c-1 c11)
 	(block-at grass c4 c-1 c11)
 
	(block-at grass c5 c-1 c11)
 	(block-at grass c6 c-1 c11)
 	(block-at grass c7 c-1 c11)
 	(block-at grass c8 c-1 c11)
 
	(block-at grass c9 c-1 c11)
 	(block-at grass c10 c-1 c11)
 	(block-at grass c11 c-1 c11)
 	(block-at grass c11 c-1 c10)
 
	(block-at grass c11 c-1 c9)
 	(block-at grass c11 c-1 c8)
 	(block-at grass c11 c-1 c7)
 	(block-at grass c11 c-1 c6)
 
	(block-at grass c11 c-1 c5)
 	(block-at grass c11 c-1 c4)
 	(block-at grass c11 c-1 c3)
 	(block-at grass c11 c-1 c2)
	)
	(:goal (and 
	(block-at oak-wood c1 c-1 c1) 		(block-at oak-wood c2 c-1 c1)
 	(block-at oak-wood c3 c-1 c1) 		(block-at oak-wood c4 c-1 c1)
 	(block-at oak-wood c5 c-1 c1) 		(block-at oak-wood c6 c-1 c1)
 	(block-at oak-wood c7 c-1 c1) 		(block-at oak-wood c8 c-1 c1)
 	(block-at oak-wood c9 c-1 c1) 		(block-at oak-wood c10 c-1 c1)
	(block-at oak-wood c11 c-1 c1) 		(block-at oak-wood c1 c-1 c2)
 	(block-at oak-wood c1 c-1 c3) 		(block-at oak-wood c1 c-1 c4)
	(block-at oak-wood c1 c-1 c5) 		(block-at oak-wood c1 c-1 c6)
 	(block-at oak-wood c1 c-1 c7) 		(block-at oak-wood c1 c-1 c8)
 	(block-at oak-wood c1 c-1 c9) 		(block-at oak-wood c1 c-1 c10)
	(block-at oak-wood c1 c-1 c11) 		(block-at oak-wood c2 c-1 c11)
 	(block-at oak-wood c3 c-1 c11) 		(block-at oak-wood c4 c-1 c11)
 	(block-at oak-wood c5 c-1 c11) 		(block-at oak-wood c6 c-1 c11)
 	(block-at oak-wood c7 c-1 c11) 		(block-at oak-wood c8 c-1 c11)
 	(block-at oak-wood c9 c-1 c11) 		(block-at oak-wood c10 c-1 c11)
	(block-at oak-wood c11 c-1 c11) 	(block-at oak-wood c11 c-1 c10)
 	(block-at oak-wood c11 c-1 c9) 		(block-at oak-wood c11 c-1 c8)
 	(block-at oak-wood c11 c-1 c7) 		(block-at oak-wood c11 c-1 c6)
 	(block-at oak-wood c11 c-1 c5) 		(block-at oak-wood c11 c-1 c4)
	(block-at oak-wood c11 c-1 c3) 		(block-at oak-wood c11 c-1 c2)	
	(block-at spruce-wood-plank c2 c0 c2) 	(block-at spruce-wood-slab c3 c0 c2)
 	(block-at spruce-wood-slab c4 c0 c2) 	(block-at spruce-wood-slab c5 c0 c2)
 	(block-at spruce-wood-plank c6 c0 c2) 	(block-at spruce-wood-stair c7 c0 c2)
	(block-at spruce-wood-plank c8 c0 c2) 	(block-at spruce-wood-slab c9 c0 c2)
	(block-at spruce-wood-plank c10 c0 c2) 	(block-at spruce-wood-slab c10 c0 c3)
 	(block-at spruce-wood-slab c10 c0 c4) 	(block-at spruce-wood-slab c10 c0 c5)
 	(block-at spruce-wood-slab c10 c0 c6) 	(block-at spruce-wood-slab c10 c0 c7)
 	(block-at spruce-wood-slab c10 c0 c8) 	(block-at spruce-wood-slab c10 c0 c9) 
	(block-at spruce-wood-plank c10 c0 c10) (block-at spruce-wood-slab c9 c0 c10)
	(block-at spruce-wood-slab c8 c0 c10) 	(block-at spruce-wood-slab c7 c0 c10)
 	(block-at spruce-wood-slab c6 c0 c10) 	(block-at spruce-wood-slab c5 c0 c10)
 	(block-at spruce-wood-slab c4 c0 c10) 	(block-at spruce-wood-slab c3 c0 c10)
	(block-at spruce-wood-plank c2 c0 c10) 	(block-at spruce-wood-slab c2 c0 c9)
 	(block-at spruce-wood-slab c2 c0 c8) 	(block-at spruce-wood-slab c2 c0 c7)
 	(block-at spruce-wood-slab c2 c0 c6) 	(block-at spruce-wood-slab c2 c0 c5)
 	(block-at spruce-wood-slab c2 c0 c4)	(block-at spruce-wood-slab c2 c0 c3)
	(block-at spruce-wood-slab c3 c0 c3)	(block-at spruce-wood-slab c3 c0 c4)
 	(block-at spruce-wood-slab c4 c0 c3)	(block-at spruce-wood-slab c4 c0 c4)
 	(block-at spruce-wood-slab c5 c0 c3)	(block-at spruce-wood-slab c5 c0 c4)
	(block-at spruce-wood-slab c6 c0 c3)	(block-at spruce-wood-slab c6 c0 c4)
	(block-at spruce-wood-slab c7 c0 c3)	(block-at spruce-wood-slab c7 c0 c4)
 	(block-at spruce-wood-slab c8 c0 c3)	(block-at spruce-wood-slab c8 c0 c4)
 	(block-at spruce-wood-slab c9 c0 c3)	(block-at spruce-wood-slab c9 c0 c4)
 	(block-at brick c3 c0 c5)		(block-at brick c3 c0 c6)
 	(block-at brick c3 c0 c7)		(block-at brick c3 c0 c8)
 	(block-at brick c3 c0 c9)		(block-at brick c4 c0 c5)
 	(block-at brick c4 c0 c6)		(block-at brick c4 c0 c7)
 	(block-at brick c4 c0 c8)		(block-at brick c4 c0 c9)
 	(block-at brick c5 c0 c5)		(block-at brick c5 c0 c6)
 	(block-at brick c5 c0 c7)		(block-at brick c5 c0 c8)
 	(block-at brick c5 c0 c9)		(block-at brick c6 c0 c5)
 	(block-at brick c6 c0 c6)		(block-at brick c6 c0 c7)
 	(block-at brick c6 c0 c8)		(block-at brick c6 c0 c9)
 	(block-at brick c7 c0 c5)		(block-at brick c7 c0 c6)
 	(block-at brick c7 c0 c7)		(block-at brick c7 c0 c8)
 	(block-at brick c7 c0 c9)		(block-at brick c8 c0 c5)
 	(block-at brick c8 c0 c6)		(block-at brick c8 c0 c7)
 	(block-at brick c8 c0 c8)

	(block-at brick c8 c0 c9)
 	(block-at brick c9 c0 c5)
 	(block-at brick c9 c0 c6)
 	(block-at brick c9 c0 c7)

	(block-at brick c9 c0 c8)
 	(block-at brick c9 c0 c9)	
	(block-at oak-wood c3 c1 c5)
 	(block-at oak-wood c3 c2 c5)
 	(block-at oak-wood c3 c3 c5)
 	(block-at oak-wood c3 c1 c9)
 
	(block-at oak-wood c3 c2 c9)
 	(block-at oak-wood c3 c3 c9)
 	(block-at oak-wood c9 c1 c5)
 	(block-at oak-wood c9 c2 c5)
 
	(block-at oak-wood c9 c3 c5)
 	(block-at oak-wood c9 c1 c9)
	(block-at oak-wood c9 c2 c9)
 	(block-at oak-wood c9 c3 c9)
	(block-at oak-wood-plank c3 c1 c6)
 	(block-at oak-wood-plank c3 c2 c6)
 	(block-at oak-wood-plank c3 c3 c6)
 
	(block-at oak-wood-stair c3 c1 c7)
 	(block-at glass-pane c3 c2 c7)
 	(block-at oak-wood-stair c3 c3 c7)
	
	(block-at oak-wood-plank c3 c1 c8) (block-at oak-wood-plank c3 c2 c8)
 	(block-at oak-wood-plank c3 c3 c8)
	(block-at oak-wood-plank c9 c1 c6)
 	(block-at oak-wood-plank c9 c2 c6)
 	(block-at oak-wood-plank c9 c3 c6)
 
	(block-at oak-wood-stair c9 c1 c7)
 	(block-at glass-pane c9 c2 c7)
 	(block-at oak-wood-stair c9 c3 c7)
	
	(block-at oak-wood-plank c9 c1 c8) (block-at oak-wood-plank c9 c2 c8)
 	(block-at oak-wood-plank c9 c3 c8)

	
	(block-at oak-wood-plank c4 c1 c9)
 	(block-at oak-wood-plank c4 c2 c9)
 	(block-at oak-wood-plank c4 c3 c9)
	(block-at oak-wood-plank c5 c1 c9)
 	(block-at glass-pane c5 c2 c9)
 	(block-at oak-wood-plank c5 c3 c9)
	(block-at oak-wood-plank c6 c1 c9)
 	(block-at oak-wood-plank c6 c2 c9)
 	(block-at oak-wood-plank c6 c3 c9)
	(block-at oak-wood-plank c7 c1 c9)
 	(block-at glass-pane c7 c2 c9)
 	(block-at oak-wood-plank c7 c3 c9)
	(block-at oak-wood-plank c8 c1 c9)
 	(block-at oak-wood-plank c8 c2 c9)
 	(block-at oak-wood-plank c8 c3 c9)
	(block-at oak-wood-plank c4 c1 c5)
 	(block-at oak-wood-plank c4 c2 c5)
 	(block-at oak-wood-plank c4 c3 c5)
	(block-at oak-wood-plank c5 c1 c5)
 	(block-at glass-pane c5 c2 c5)
 	(block-at oak-wood-plank c5 c3 c5)
	(block-at oak-wood-plank c6 c1 c5)
 	(block-at oak-wood-plank c6 c2 c5)
 	(block-at oak-wood-plank c6 c3 c5)
	(block-at oak-door c7 c1 c5)
 	(block-at oak-door c7 c2 c5)
 	(block-at oak-wood-plank c7 c3 c5)
	(block-at oak-wood-plank c8 c1 c5)
 	(block-at oak-wood-plank c8 c2 c5)
 	(block-at oak-wood-plank c8 c3 c5)
	(block-at spruce-wood-plank c3 c4 c6)
 	(block-at spruce-wood-plank c3 c4 c7)
 	(block-at spruce-wood-plank c3 c4 c8)
 
	(block-at spruce-wood-plank c4 c4 c6)
 	(block-at spruce-wood-plank c4 c4 c7)
 	(block-at spruce-wood-plank c4 c4 c8)
	
	(block-at spruce-wood-plank c5 c4 c6) (block-at spruce-wood-plank c5 c4 c7)
 	(block-at spruce-wood-plank c5 c4 c8)
	
	(block-at spruce-wood-plank c6 c4 c6)
 	(block-at spruce-wood-plank c6 c4 c7)
 	(block-at spruce-wood-plank c6 c4 c8)
 
	(block-at spruce-wood-plank c7 c4 c6)
 	(block-at spruce-wood-plank c7 c4 c7)
 	(block-at spruce-wood-plank c7 c4 c8)
	
	(block-at spruce-wood-plank c8 c4 c6) (block-at spruce-wood-plank c8 c4 c7)
 	(block-at spruce-wood-plank c8 c4 c8)
	
	(block-at spruce-wood-plank c9 c4 c6)
 	(block-at spruce-wood-plank c9 c4 c7)
 	(block-at spruce-wood-plank c9 c4 c8)	
	(block-at spruce-wood-plank c3 c5 c7)
 	(block-at spruce-wood-plank c4 c5 c7)
 	(block-at spruce-wood-plank c5 c5 c7)
 
	(block-at spruce-wood-plank c6 c5 c7)
 	(block-at spruce-wood-plank c7 c5 c7)
 	(block-at spruce-wood-plank c8 c5 c7)
	
	(block-at spruce-wood-plank c9 c5 c7) (block-at spruce-wood-plank c3 c3 c4)
 	(block-at spruce-wood-plank c9 c3 c4)
	
	(block-at spruce-wood-slab c4 c3 c4)
 	(block-at spruce-wood-slab c5 c3 c4)
 	(block-at spruce-wood-slab c6 c3 c4)
 
	(block-at spruce-wood-slab c7 c3 c4)
 	(block-at spruce-wood-slab c8 c3 c4)
 	(block-at spruce-wood-slab c10 c3 c4)
	
	(block-at spruce-wood-slab c10 c3 c3) (block-at spruce-wood-slab c9 c3 c3)
 	(block-at spruce-wood-slab c8 c3 c3)
	
	(block-at spruce-wood-slab c7 c3 c3)
 	(block-at spruce-wood-slab c6 c3 c3)
 	(block-at spruce-wood-slab c5 c3 c3)	
	(block-at spruce-wood-slab c4 c3 c3)
 	(block-at spruce-wood-slab c3 c3 c3)
 	(block-at spruce-wood-slab c2 c3 c3)
 
	(block-at spruce-wood-slab c2 c3 c4)
 	(block-at spruce-wood-slab c3 c3 c10)
 	(block-at spruce-wood-slab c2 c3 c10)
	
	(block-at spruce-wood-slab c4 c3 c10) (block-at spruce-wood-slab c5 c3 c10)
 	(block-at spruce-wood-slab c6 c3 c10)
	
	(block-at spruce-wood-slab c7 c3 c10)
 	(block-at spruce-wood-slab c8 c3 c10)
 	(block-at spruce-wood-slab c9 c3 c10)
 
	(block-at spruce-wood-slab c10 c3 c10)
 	(block-at spruce-wood-slab c3 c5 c8)
 	(block-at spruce-wood-slab c2 c5 c8)
	
	(block-at spruce-wood-slab c4 c5 c8) (block-at spruce-wood-slab c5 c5 c8)
 	(block-at spruce-wood-slab c6 c5 c8)
	
	(block-at spruce-wood-slab c7 c5 c8)
 	(block-at spruce-wood-slab c8 c5 c8)
 	(block-at spruce-wood-slab c9 c5 c8)
 
	(block-at spruce-wood-slab c10 c5 c8) (block-at spruce-wood-slab c3 c5 c6)
 	(block-at spruce-wood-slab c2 c5 c6)
	
	(block-at spruce-wood-slab c4 c5 c6) (block-at spruce-wood-slab c5 c5 c6)
 	(block-at spruce-wood-slab c6 c5 c6)
	
	(block-at spruce-wood-slab c7 c5 c6)
 	(block-at spruce-wood-slab c8 c5 c6)
 	(block-at spruce-wood-slab c9 c5 c6)
 
	(block-at spruce-wood-slab c10 c5 c6)
	(block-at spruce-wood-stair c3 c4 c5)
 	(block-at spruce-wood-stair c2 c4 c5)
	
	(block-at spruce-wood-stair c4 c4 c5) (block-at spruce-wood-stair c5 c4 c5)
 	(block-at spruce-wood-stair c6 c4 c5)
	
	(block-at spruce-wood-stair c7 c4 c5)
 	(block-at spruce-wood-stair c8 c4 c5)
 	(block-at spruce-wood-stair c9 c4 c5)
 
	(block-at spruce-wood-stair c10 c4 c5) (block-at spruce-wood-stair c3 c4 c9)
 	(block-at spruce-wood-stair c2 c4 c9)
	
	(block-at spruce-wood-stair c4 c4 c9) (block-at spruce-wood-stair c5 c4 c9)
 	(block-at spruce-wood-stair c6 c4 c9)
	
	(block-at spruce-wood-stair c7 c4 c9)
 	(block-at spruce-wood-stair c8 c4 c9)
 	(block-at spruce-wood-stair c9 c4 c9)
 
	(block-at spruce-wood-stair c10 c4 c9) (block-at spruce-wood-slab c10 c5 c7)
 	(block-at spruce-wood-slab c2 c5 c7)
	
	(block-at spruce-wood-stair c2 c4 c8) (block-at spruce-wood-stair c2 c4 c6)
 	(block-at spruce-wood-stair c10 c4 c8)
	
	(block-at spruce-wood-stair c10 c4 c6)

	(block-at oak-leaf c11 c0 c1)
 	(block-at oak-leaf c11 c1 c1)
 	(block-at oak-leaf c11 c0 c2)
 	(block-at oak-leaf c11 c1 c2)
	(block-at oak-leaf c11 c0 c3)
 	(block-at oak-leaf c11 c1 c3)
 	(block-at oak-leaf c11 c0 c4)
 	(block-at oak-leaf c11 c1 c4)

	(block-at oak-leaf c11 c0 c5)
 	(block-at oak-leaf c11 c1 c5)
 	(block-at oak-leaf c11 c0 c6)
 	(block-at oak-leaf c11 c1 c6)

	(block-at oak-leaf c11 c0 c7)
 	(block-at oak-leaf c11 c1 c7)
 	(block-at oak-leaf c11 c0 c8)
 	(block-at oak-leaf c11 c1 c8)

	(block-at oak-leaf c11 c0 c9)
 	(block-at oak-leaf c11 c1 c9)
 	(block-at oak-leaf c11 c0 c10)
 	(block-at oak-leaf c11 c1 c10)

	(block-at oak-leaf c11 c0 c11)
 	(block-at oak-leaf c11 c1 c11)
 	(block-at oak-leaf c10 c0 c11)
 	(block-at oak-leaf c10 c1 c11)

	(block-at oak-leaf c9 c0 c11)
 	(block-at oak-leaf c9 c1 c11)
 	(block-at oak-leaf c8 c0 c11)
 	(block-at oak-leaf c8 c1 c11)
	(block-at oak-leaf c7 c0 c11)
 	(block-at oak-leaf c7 c1 c11)
 	(block-at oak-leaf c6 c0 c11)
 	(block-at oak-leaf c6 c1 c11)

	(block-at oak-leaf c5 c0 c11)
 	(block-at oak-leaf c5 c1 c11)
 	(block-at oak-leaf c4 c0 c11)
 	(block-at oak-leaf c4 c1 c11)

	(block-at oak-leaf c3 c0 c11)
 	(block-at oak-leaf c3 c1 c11)
 	(block-at oak-leaf c2 c0 c11)
 	(block-at oak-leaf c2 c1 c11)

	(block-at oak-leaf c1 c0 c11)
 	(block-at oak-leaf c1 c1 c11)
 	(block-at oak-leaf c1 c0 c10)
 	(block-at oak-leaf c1 c1 c10)

	(block-at oak-leaf c1 c0 c9)
 	(block-at oak-leaf c1 c1 c9)
 	(block-at oak-leaf c1 c0 c8)
 	(block-at oak-leaf c1 c1 c8)

	(block-at oak-leaf c1 c0 c7)
 	(block-at oak-leaf c1 c1 c7)
 	(block-at oak-leaf c1 c0 c6)
 	(block-at oak-leaf c1 c1 c6)

	(block-at oak-leaf c1 c0 c5)
 	(block-at oak-leaf c1 c1 c5)
 	(block-at oak-leaf c1 c0 c4)
 	(block-at oak-leaf c1 c1 c4)
	(block-at oak-leaf c1 c0 c3)
 	(block-at oak-leaf c1 c1 c3)
 	(block-at oak-leaf c1 c0 c2)
 	(block-at oak-leaf c1 c1 c2)

	(block-at oak-leaf c1 c0 c1)
 	(block-at oak-leaf c1 c1 c1)
 	(block-at oak-leaf c2 c0 c1)
 	(block-at oak-leaf c2 c1 c1)

	(block-at oak-leaf c3 c0 c1)
 	(block-at oak-leaf c3 c1 c1)
 	(block-at oak-leaf c4 c0 c1)
 	(block-at oak-leaf c4 c1 c1)

	(block-at oak-leaf c5 c0 c1)
 	(block-at oak-leaf c9 c0 c1)
 	(block-at oak-leaf c10 c0 c1)
 	(block-at oak-leaf c10 c1 c1)
	(block-at oak-fence c10 c1 c5) (block-at oak-fence c10 c1 c4)
 	(block-at oak-fence c10 c1 c3)
	
	(block-at oak-fence c10 c1 c2)
 	(block-at oak-fence c9 c1 c2)
 	(block-at oak-fence c8 c1 c2)
 
	(block-at oak-fence c6 c1 c2) (block-at oak-fence c5 c1 c2)
 	(block-at oak-fence c4 c1 c2)
	
	(block-at oak-fence c3 c1 c2) (block-at oak-fence c2 c1 c2)
 	(block-at oak-fence c2 c1 c3)
	
	(block-at oak-fence c2 c1 c4)
 	(block-at oak-fence c2 c1 c5)
 	(block-at oak-fence c2 c1 c10)
 
	(block-at oak-fence c10 c1 c10) (block-at torch c10 c2 c2)
 	(block-at torch c10 c2 c10)
	
	(block-at torch c2 c2 c10) (block-at torch c2 c2 c2)
 	(block-at oak-wood-stair c3 c1 c3)
	(block-at oak-wood-stair c5 c1 c3) (block-at oak-fence c4 c1 c3)
 	(block-at wooden-pressure-plate c4 c2 c3)
	)
	)
	(:metric minimize (total-cost))
)
